name: adyen_payment
description: Library for working with payment api of Adyen
publish_to: "none"
version: 0.0.2-dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  json_annotation: ^4.7.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.4.0

flutter:
  uses-material-design: true
